---
# Play 1: Install NFS utilities on all nodes and configure exports on servers
- name: Setup NFS on all nodes
  hosts: all
  become: true
  roles:
    - geerlingguy.nfs

# Play 2: Mount NFS exports on clients
- name: Mount NFS exports on clients
  hosts: nfs_clients
  become: true
  vars:
    nfs_server_host: "{{ groups['nfs_servers'] | first }}"
    nfs_client_mounts:
      - src: "{{ hostvars[nfs_server_host].ansible_host | default(nfs_server_host) }}:/srv"
        path: /mnt/nfs/srv
        opts: "ro,sync"
      - src: "{{ hostvars[nfs_server_host].ansible_host | default(nfs_server_host) }}:/home"
        path: /mnt/nfs/home
        opts: "rw,sync"
      - src: "{{ hostvars[nfs_server_host].ansible_host | default(nfs_server_host) }}:/scratch"
        path: /mnt/nfs/scratch
        opts: "rw,async"
  tasks:
    - name: Ensure client mount directories exist
      file:
        path: "{{ item.path }}"
        state: directory
        mode: '0755'
      loop: "{{ nfs_client_mounts }}"

    - name: Mount NFS shares (fstab + mounted)
      ansible.posix.mount:
        src: "{{ item.src }}"
        path: "{{ item.path }}"
        fstype: nfs
        opts: "{{ item.opts }}"
        state: mounted
      loop: "{{ nfs_client_mounts }}"
