---
all:
  hosts:
    node1:
      ansible_host: 192.168.1.101
    node2:
      ansible_host: 192.168.1.102
  children:
    nfs_servers:
      hosts:
        node1:
    nfs_clients:
      hosts:
        node2: